package com.wanma.domain;

// Generated 2013-12-25 15:12:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AlarmLog generated by hbm2java
 */
public class AlarmLog implements java.io.Serializable {

	private int id;
	private String ifieldAddress;
	private String deviceType;
	private String deviceCode;
	private String deviceName;
	private String board;
	private String port;
	private Integer alarmtype;
	private Date logtime;

	public AlarmLog() {
	}

	public AlarmLog(int id) {
		this.id = id;
	}

	public AlarmLog(int id, String ifieldAddress, String deviceType,
			String deviceCode, String deviceName, String board, String port,
			Integer alarmtype, Date logtime) {
		this.id = id;
		this.ifieldAddress = ifieldAddress;
		this.deviceType = deviceType;
		this.deviceCode = deviceCode;
		this.deviceName = deviceName;
		this.board = board;
		this.port = port;
		this.alarmtype = alarmtype;
		this.logtime = logtime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIfieldAddress() {
		return this.ifieldAddress;
	}

	public void setIfieldAddress(String ifieldAddress) {
		this.ifieldAddress = ifieldAddress;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	public String getBoard() {
		return this.board;
	}

	public void setBoard(String board) {
		this.board = board;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public Integer getAlarmtype() {
		return this.alarmtype;
	}

	public void setAlarmtype(Integer alarmtype) {
		this.alarmtype = alarmtype;
	}

	public Date getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Date logtime) {
		this.logtime = logtime;
	}

}
