package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * Cabinet generated by hbm2java
 */
public class Cabinet implements java.io.Serializable {

	private String code;
	private String name;
	private String station;
	private String hostRoom;
	private String mpuSoftwareVersion;
	private String mpuHardwareVersion;
	private String mpuSpecification;
	private String type;
	private Double latitude;
	private Double longtitude;
	private String address;
	private String manufacture;
	private int cabinetId;
	private String importTag;

	public Cabinet() {
	}

	public Cabinet(String code, int cabinetId) {
		this.code = code;
		this.cabinetId = cabinetId;
	}

	public Cabinet(String code, String name, String station, String hostRoom,
			String mpuSoftwareVersion, String mpuHardwareVersion,
			String mpuSpecification, String type, Double latitude,
			Double longtitude, String address, String manufacture,
			int cabinetId, String importTag) {
		this.code = code;
		this.name = name;
		this.station = station;
		this.hostRoom = hostRoom;
		this.mpuSoftwareVersion = mpuSoftwareVersion;
		this.mpuHardwareVersion = mpuHardwareVersion;
		this.mpuSpecification = mpuSpecification;
		this.type = type;
		this.latitude = latitude;
		this.longtitude = longtitude;
		this.address = address;
		this.manufacture = manufacture;
		this.cabinetId = cabinetId;
		this.importTag = importTag;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getHostRoom() {
		return this.hostRoom;
	}

	public void setHostRoom(String hostRoom) {
		this.hostRoom = hostRoom;
	}

	public String getMpuSoftwareVersion() {
		return this.mpuSoftwareVersion;
	}

	public void setMpuSoftwareVersion(String mpuSoftwareVersion) {
		this.mpuSoftwareVersion = mpuSoftwareVersion;
	}

	public String getMpuHardwareVersion() {
		return this.mpuHardwareVersion;
	}

	public void setMpuHardwareVersion(String mpuHardwareVersion) {
		this.mpuHardwareVersion = mpuHardwareVersion;
	}

	public String getMpuSpecification() {
		return this.mpuSpecification;
	}

	public void setMpuSpecification(String mpuSpecification) {
		this.mpuSpecification = mpuSpecification;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(Double longtitude) {
		this.longtitude = longtitude;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getManufacture() {
		return this.manufacture;
	}

	public void setManufacture(String manufacture) {
		this.manufacture = manufacture;
	}

	public int getCabinetId() {
		return this.cabinetId;
	}

	public void setCabinetId(int cabinetId) {
		this.cabinetId = cabinetId;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
