package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * CableSpan generated by hbm2java
 */
public class CableSpan implements java.io.Serializable {

	private String code;
	private String name;
	private String parentCode;
	private String assemblyName;
	private String assemblyNumber;
	private String structureType;
	private String ameType;
	private String zmeType;
	private String ameCode;
	private String zmeCode;
	private String manufacturer;
	private String phyStatue;
	private String serviceStatue;
	private Integer length;
	private Integer fiberLength;
	private Integer fiberNumber;
	private String fiberType;
	private String fiberModel;
	private String shapeLine;
	private String layingMethod;
	private String notes;
	private String importTag;
	private Integer diskRemainLength;
	private String diskRemainType;
	private String dataAcquisitionTime;
	private String acquisitoner;
	private String spectrum;
	private String localNetwork;
	private Boolean loclaOrRemote;
	private Double dispersion;
	private String projectNum;
	private String projectStatus;

	public CableSpan() {
	}

	public CableSpan(String code) {
		this.code = code;
	}

	public CableSpan(String code, String name, String parentCode,
			String assemblyName, String assemblyNumber, String structureType,
			String ameType, String zmeType, String ameCode, String zmeCode,
			String manufacturer, String phyStatue, String serviceStatue,
			Integer length, Integer fiberLength, Integer fiberNumber,
			String fiberType, String fiberModel, String shapeLine,
			String layingMethod, String notes, String importTag,
			Integer diskRemainLength, String diskRemainType,
			String dataAcquisitionTime, String acquisitoner, String spectrum,
			String localNetwork, Boolean loclaOrRemote, Double dispersion,
			String projectNum, String projectStatus) {
		this.code = code;
		this.name = name;
		this.parentCode = parentCode;
		this.assemblyName = assemblyName;
		this.assemblyNumber = assemblyNumber;
		this.structureType = structureType;
		this.ameType = ameType;
		this.zmeType = zmeType;
		this.ameCode = ameCode;
		this.zmeCode = zmeCode;
		this.manufacturer = manufacturer;
		this.phyStatue = phyStatue;
		this.serviceStatue = serviceStatue;
		this.length = length;
		this.fiberLength = fiberLength;
		this.fiberNumber = fiberNumber;
		this.fiberType = fiberType;
		this.fiberModel = fiberModel;
		this.shapeLine = shapeLine;
		this.layingMethod = layingMethod;
		this.notes = notes;
		this.importTag = importTag;
		this.diskRemainLength = diskRemainLength;
		this.diskRemainType = diskRemainType;
		this.dataAcquisitionTime = dataAcquisitionTime;
		this.acquisitoner = acquisitoner;
		this.spectrum = spectrum;
		this.localNetwork = localNetwork;
		this.loclaOrRemote = loclaOrRemote;
		this.dispersion = dispersion;
		this.projectNum = projectNum;
		this.projectStatus = projectStatus;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getAssemblyName() {
		return this.assemblyName;
	}

	public void setAssemblyName(String assemblyName) {
		this.assemblyName = assemblyName;
	}

	public String getAssemblyNumber() {
		return this.assemblyNumber;
	}

	public void setAssemblyNumber(String assemblyNumber) {
		this.assemblyNumber = assemblyNumber;
	}

	public String getStructureType() {
		return this.structureType;
	}

	public void setStructureType(String structureType) {
		this.structureType = structureType;
	}

	public String getAmeType() {
		return this.ameType;
	}

	public void setAmeType(String ameType) {
		this.ameType = ameType;
	}

	public String getZmeType() {
		return this.zmeType;
	}

	public void setZmeType(String zmeType) {
		this.zmeType = zmeType;
	}

	public String getAmeCode() {
		return this.ameCode;
	}

	public void setAmeCode(String ameCode) {
		this.ameCode = ameCode;
	}

	public String getZmeCode() {
		return this.zmeCode;
	}

	public void setZmeCode(String zmeCode) {
		this.zmeCode = zmeCode;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getPhyStatue() {
		return this.phyStatue;
	}

	public void setPhyStatue(String phyStatue) {
		this.phyStatue = phyStatue;
	}

	public String getServiceStatue() {
		return this.serviceStatue;
	}

	public void setServiceStatue(String serviceStatue) {
		this.serviceStatue = serviceStatue;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Integer getFiberLength() {
		return this.fiberLength;
	}

	public void setFiberLength(Integer fiberLength) {
		this.fiberLength = fiberLength;
	}

	public Integer getFiberNumber() {
		return this.fiberNumber;
	}

	public void setFiberNumber(Integer fiberNumber) {
		this.fiberNumber = fiberNumber;
	}

	public String getFiberType() {
		return this.fiberType;
	}

	public void setFiberType(String fiberType) {
		this.fiberType = fiberType;
	}

	public String getFiberModel() {
		return this.fiberModel;
	}

	public void setFiberModel(String fiberModel) {
		this.fiberModel = fiberModel;
	}

	public String getShapeLine() {
		return this.shapeLine;
	}

	public void setShapeLine(String shapeLine) {
		this.shapeLine = shapeLine;
	}

	public String getLayingMethod() {
		return this.layingMethod;
	}

	public void setLayingMethod(String layingMethod) {
		this.layingMethod = layingMethod;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

	public Integer getDiskRemainLength() {
		return this.diskRemainLength;
	}

	public void setDiskRemainLength(Integer diskRemainLength) {
		this.diskRemainLength = diskRemainLength;
	}

	public String getDiskRemainType() {
		return this.diskRemainType;
	}

	public void setDiskRemainType(String diskRemainType) {
		this.diskRemainType = diskRemainType;
	}

	public String getDataAcquisitionTime() {
		return this.dataAcquisitionTime;
	}

	public void setDataAcquisitionTime(String dataAcquisitionTime) {
		this.dataAcquisitionTime = dataAcquisitionTime;
	}

	public String getAcquisitoner() {
		return this.acquisitoner;
	}

	public void setAcquisitoner(String acquisitoner) {
		this.acquisitoner = acquisitoner;
	}

	public String getSpectrum() {
		return this.spectrum;
	}

	public void setSpectrum(String spectrum) {
		this.spectrum = spectrum;
	}

	public String getLocalNetwork() {
		return this.localNetwork;
	}

	public void setLocalNetwork(String localNetwork) {
		this.localNetwork = localNetwork;
	}

	public Boolean getLoclaOrRemote() {
		return this.loclaOrRemote;
	}

	public void setLoclaOrRemote(Boolean loclaOrRemote) {
		this.loclaOrRemote = loclaOrRemote;
	}

	public Double getDispersion() {
		return this.dispersion;
	}

	public void setDispersion(Double dispersion) {
		this.dispersion = dispersion;
	}

	public String getProjectNum() {
		return this.projectNum;
	}

	public void setProjectNum(String projectNum) {
		this.projectNum = projectNum;
	}

	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

}
