package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cable generated by hbm2java
 */
public class Cable implements java.io.Serializable {

	private String code;
	private String name;
	private Integer length;
	private String category;
	private String notes;
	private String assemblyName;
	private String assemblyNumber;
	private String cableType;
	private String topology;
	private Date createTime;
	private Date reviseTime;
	private String stationCode;
	private String phyStatue;
	private String serviceStatue;
	private String importTag;

	public Cable() {
	}

	public Cable(String code) {
		this.code = code;
	}

	public Cable(String code, String name, Integer length, String category,
			String notes, String assemblyName, String assemblyNumber,
			String cableType, String topology, Date createTime,
			Date reviseTime, String stationCode, String phyStatue,
			String serviceStatue, String importTag) {
		this.code = code;
		this.name = name;
		this.length = length;
		this.category = category;
		this.notes = notes;
		this.assemblyName = assemblyName;
		this.assemblyNumber = assemblyNumber;
		this.cableType = cableType;
		this.topology = topology;
		this.createTime = createTime;
		this.reviseTime = reviseTime;
		this.stationCode = stationCode;
		this.phyStatue = phyStatue;
		this.serviceStatue = serviceStatue;
		this.importTag = importTag;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getAssemblyName() {
		return this.assemblyName;
	}

	public void setAssemblyName(String assemblyName) {
		this.assemblyName = assemblyName;
	}

	public String getAssemblyNumber() {
		return this.assemblyNumber;
	}

	public void setAssemblyNumber(String assemblyNumber) {
		this.assemblyNumber = assemblyNumber;
	}

	public String getCableType() {
		return this.cableType;
	}

	public void setCableType(String cableType) {
		this.cableType = cableType;
	}

	public String getTopology() {
		return this.topology;
	}

	public void setTopology(String topology) {
		this.topology = topology;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getReviseTime() {
		return this.reviseTime;
	}

	public void setReviseTime(Date reviseTime) {
		this.reviseTime = reviseTime;
	}

	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	public String getPhyStatue() {
		return this.phyStatue;
	}

	public void setPhyStatue(String phyStatue) {
		this.phyStatue = phyStatue;
	}

	public String getServiceStatue() {
		return this.serviceStatue;
	}

	public void setServiceStatue(String serviceStatue) {
		this.serviceStatue = serviceStatue;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
