package com.wanma.domain;

// Generated 2013-12-18 10:42:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ConfigTask generated by hbm2java
 */
public class ConfigTask implements java.io.Serializable {

	private String code;
	private String name;
	private String groupId;
	private String workerId;
	private String deviceCode;
	private String deviceType;
	private String deviceName;
	private String result;
	private String creator;
	private Date createTime;
	private Date deadline;
	private Date finishedTime;
	private Short status;
	private String station;
	private String hostroom;

	public ConfigTask() {
	}

	public ConfigTask(String code) {
		this.code = code;
	}

	public ConfigTask(String code, String name, String groupId,
			String workerId, String deviceCode, String deviceType,
			String deviceName, String result, String creator, Date createTime,
			Date deadline, Date finishedTime, Short status, String station,
			String hostroom) {
		this.code = code;
		this.name = name;
		this.groupId = groupId;
		this.workerId = workerId;
		this.deviceCode = deviceCode;
		this.deviceType = deviceType;
		this.deviceName = deviceName;
		this.result = result;
		this.creator = creator;
		this.createTime = createTime;
		this.deadline = deadline;
		this.finishedTime = finishedTime;
		this.status = status;
		this.station = station;
		this.hostroom = hostroom;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getWorkerId() {
		return this.workerId;
	}

	public void setWorkerId(String workerId) {
		this.workerId = workerId;
	}

	public String getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	public Date getFinishedTime() {
		return this.finishedTime;
	}

	public void setFinishedTime(Date finishedTime) {
		this.finishedTime = finishedTime;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getHostroom() {
		return this.hostroom;
	}

	public void setHostroom(String hostroom) {
		this.hostroom = hostroom;
	}

}
