package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

	private String districtName;
	private String zipCode;

	public District() {
	}

	public District(String districtName) {
		this.districtName = districtName;
	}

	public District(String districtName, String zipCode) {
		this.districtName = districtName;
		this.zipCode = zipCode;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

}
