package com.wanma.domain;

// Generated 2013-12-18 14:08:18 by Hibernate Tools 3.4.0.CR1

/**
 * Fiber generated by hbm2java
 */
public class Fiber implements java.io.Serializable {

	private String code;
	private String name;
	private String parentCode;
	private int logicalNo;
	private Integer fiberSque;
	private Integer length;
	private String ameType;
	private String zmeType;
	private String ameCode;
	private String zmeCode;
	private String acard;
	private String zcard;
	private String aportCode;
	private String zportCode;
	private String spectrum;
	private String serviceStatue;
	private String importTag;

	public Fiber() {
	}

	public Fiber(String code, String name, String parentCode, int logicalNo) {
		this.code = code;
		this.name = name;
		this.parentCode = parentCode;
		this.logicalNo = logicalNo;
	}

	public Fiber(String code, String name, String parentCode, int logicalNo,
			Integer fiberSque, Integer length, String ameType, String zmeType,
			String ameCode, String zmeCode, String acard, String zcard,
			String aportCode, String zportCode, String spectrum,
			String serviceStatue, String importTag) {
		this.code = code;
		this.name = name;
		this.parentCode = parentCode;
		this.logicalNo = logicalNo;
		this.fiberSque = fiberSque;
		this.length = length;
		this.ameType = ameType;
		this.zmeType = zmeType;
		this.ameCode = ameCode;
		this.zmeCode = zmeCode;
		this.acard = acard;
		this.zcard = zcard;
		this.aportCode = aportCode;
		this.zportCode = zportCode;
		this.spectrum = spectrum;
		this.serviceStatue = serviceStatue;
		this.importTag = importTag;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public int getLogicalNo() {
		return this.logicalNo;
	}

	public void setLogicalNo(int logicalNo) {
		this.logicalNo = logicalNo;
	}

	public Integer getFiberSque() {
		return this.fiberSque;
	}

	public void setFiberSque(Integer fiberSque) {
		this.fiberSque = fiberSque;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public String getAmeType() {
		return this.ameType;
	}

	public void setAmeType(String ameType) {
		this.ameType = ameType;
	}

	public String getZmeType() {
		return this.zmeType;
	}

	public void setZmeType(String zmeType) {
		this.zmeType = zmeType;
	}

	public String getAmeCode() {
		return this.ameCode;
	}

	public void setAmeCode(String ameCode) {
		this.ameCode = ameCode;
	}

	public String getZmeCode() {
		return this.zmeCode;
	}

	public void setZmeCode(String zmeCode) {
		this.zmeCode = zmeCode;
	}

	public String getAcard() {
		return this.acard;
	}

	public void setAcard(String acard) {
		this.acard = acard;
	}

	public String getZcard() {
		return this.zcard;
	}

	public void setZcard(String zcard) {
		this.zcard = zcard;
	}

	public String getAportCode() {
		return this.aportCode;
	}

	public void setAportCode(String aportCode) {
		this.aportCode = aportCode;
	}

	public String getZportCode() {
		return this.zportCode;
	}

	public void setZportCode(String zportCode) {
		this.zportCode = zportCode;
	}

	public String getSpectrum() {
		return this.spectrum;
	}

	public void setSpectrum(String spectrum) {
		this.spectrum = spectrum;
	}

	public String getServiceStatue() {
		return this.serviceStatue;
	}

	public void setServiceStatue(String serviceStatue) {
		this.serviceStatue = serviceStatue;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
