package com.wanma.domain;

// Generated 2013-12-14 9:43:22 by Hibernate Tools 3.4.0.CR1

/**
 * Frame generated by hbm2java
 */
public class Frame implements java.io.Serializable {

	private String code;
	private String frameName;
	private String hostCabinet;
	private Integer boardsCapacity;
	private Integer portsCapacity;
	private Integer usedBoardsNumber;
	private Integer usedPortsNumber;
	private Integer numberInCabinet;
	private int frameId;
	private String importTag;
	private String status;

	public Frame() {
	}

	public Frame(String code, int frameId) {
		this.code = code;
		this.frameId = frameId;
	}

	public Frame(String code, String frameName, String hostCabinet,
			Integer boardsCapacity, Integer portsCapacity,
			Integer usedBoardsNumber, Integer usedPortsNumber,
			Integer numberInCabinet, int frameId, String importTag,
			String status) {
		this.code = code;
		this.frameName = frameName;
		this.hostCabinet = hostCabinet;
		this.boardsCapacity = boardsCapacity;
		this.portsCapacity = portsCapacity;
		this.usedBoardsNumber = usedBoardsNumber;
		this.usedPortsNumber = usedPortsNumber;
		this.numberInCabinet = numberInCabinet;
		this.frameId = frameId;
		this.importTag = importTag;
		this.status = status;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getFrameName() {
		return this.frameName;
	}

	public void setFrameName(String frameName) {
		this.frameName = frameName;
	}

	public String getHostCabinet() {
		return this.hostCabinet;
	}

	public void setHostCabinet(String hostCabinet) {
		this.hostCabinet = hostCabinet;
	}

	public Integer getBoardsCapacity() {
		return this.boardsCapacity;
	}

	public void setBoardsCapacity(Integer boardsCapacity) {
		this.boardsCapacity = boardsCapacity;
	}

	public Integer getPortsCapacity() {
		return this.portsCapacity;
	}

	public void setPortsCapacity(Integer portsCapacity) {
		this.portsCapacity = portsCapacity;
	}

	public Integer getUsedBoardsNumber() {
		return this.usedBoardsNumber;
	}

	public void setUsedBoardsNumber(Integer usedBoardsNumber) {
		this.usedBoardsNumber = usedBoardsNumber;
	}

	public Integer getUsedPortsNumber() {
		return this.usedPortsNumber;
	}

	public void setUsedPortsNumber(Integer usedPortsNumber) {
		this.usedPortsNumber = usedPortsNumber;
	}

	public Integer getNumberInCabinet() {
		return this.numberInCabinet;
	}

	public void setNumberInCabinet(Integer numberInCabinet) {
		this.numberInCabinet = numberInCabinet;
	}

	public int getFrameId() {
		return this.frameId;
	}

	public void setFrameId(int frameId) {
		this.frameId = frameId;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
