package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HostRoom generated by hbm2java
 */
public class HostRoom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8054708989630992010L;
	private String code;
	private String name;
	private String aliasName;
	private String briefName;
	private String stationName;
	private String hostType;
	private Date creatTime;
	private Date reviseTime;
	private Boolean localOrremote;
	private Integer floors;
	private Integer length;
	private Integer width;
	private Integer highth;
	private String notes;
	private String address;
	private Double latitute;
	private Double longitude;
	private String importTag;

	public HostRoom() {
	}

	public HostRoom(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public HostRoom(String code, String name, String aliasName,
			String briefName, String stationName, String hostType,
			Date creatTime, Date reviseTime, Boolean localOrremote,
			Integer floors, Integer length, Integer width, Integer highth,
			String notes, String address, Double latitute, Double longitude,
			String importTag) {
		this.code = code;
		this.name = name;
		this.aliasName = aliasName;
		this.briefName = briefName;
		this.stationName = stationName;
		this.hostType = hostType;
		this.creatTime = creatTime;
		this.reviseTime = reviseTime;
		this.localOrremote = localOrremote;
		this.floors = floors;
		this.length = length;
		this.width = width;
		this.highth = highth;
		this.notes = notes;
		this.address = address;
		this.latitute = latitute;
		this.longitude = longitude;
		this.importTag = importTag;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAliasName() {
		return this.aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	public String getBriefName() {
		return this.briefName;
	}

	public void setBriefName(String briefName) {
		this.briefName = briefName;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getHostType() {
		return this.hostType;
	}

	public void setHostType(String hostType) {
		this.hostType = hostType;
	}

	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public Date getReviseTime() {
		return this.reviseTime;
	}

	public void setReviseTime(Date reviseTime) {
		this.reviseTime = reviseTime;
	}

	public Boolean getLocalOrremote() {
		return this.localOrremote;
	}

	public void setLocalOrremote(Boolean localOrremote) {
		this.localOrremote = localOrremote;
	}

	public Integer getFloors() {
		return this.floors;
	}

	public void setFloors(Integer floors) {
		this.floors = floors;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHighth() {
		return this.highth;
	}

	public void setHighth(Integer highth) {
		this.highth = highth;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getLatitute() {
		return this.latitute;
	}

	public void setLatitute(Double latitute) {
		this.latitute = latitute;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
