package com.wanma.domain;

// Generated 2013-12-5 21:53:08 by Hibernate Tools 3.4.0.CR1

/**
 * Ifat generated by hbm2java
 */
public class Ifat implements java.io.Serializable {

	private int ifatId;
	private String name;
	private String code;
	private String assemblyType;
	private String assemblyNumber;
	private String serviceStatus;
	private String phyStatus;
	private String stationCode;
	private String stationName;
	private String structStatus;
	private String servicdeStatus;
	private String hostRoomCode;
	private String manufacturer;
	private String configurationType;
	private Boolean needSnmp;
	private Boolean needTimeSyn;
	private String ip;
	private String subnetMask;
	private String gateway;
	private Integer temperature;
	private Double longitude;
	private String targetHost;
	private String snmpVersion;
	private String hostTrapPort;
	private Boolean trapEnabled;
	private String trapHostDomain;
	private Integer capacity;
	private Integer insalledCapacity;
	private Integer hight;
	private Boolean isIntergated;
	private String installation;
	private Integer colsnum;
	private Integer blockEachCol;
	private Integer cols;
	private Integer rows;
	private String dutyPerson;
	private String oid;
	private Integer xpositon;
	private Integer ypositon;
	private Double longtitude;
	private Double latitude;
	private String importTag;
	private String model;
	private String type;

	public Ifat() {
	}

	public Ifat(int ifatId, String code) {
		this.ifatId = ifatId;
		this.code = code;
	}

	public Ifat(int ifatId, String name, String code, String assemblyType,
			String assemblyNumber, String serviceStatus, String phyStatus,
			String stationCode, String stationName, String structStatus,
			String servicdeStatus, String hostRoomCode, String manufacturer,
			String configurationType, Boolean needSnmp, Boolean needTimeSyn,
			String ip, String subnetMask, String gateway, Integer temperature,
			Double longitude, String targetHost, String snmpVersion,
			String hostTrapPort, Boolean trapEnabled, String trapHostDomain,
			Integer capacity, Integer insalledCapacity, Integer hight,
			Boolean isIntergated, String installation, Integer colsnum,
			Integer blockEachCol, Integer cols, Integer rows,
			String dutyPerson, String oid, Integer xpositon, Integer ypositon,
			Double longtitude, Double latitude, String importTag, String model,
			String type) {
		this.ifatId = ifatId;
		this.name = name;
		this.code = code;
		this.assemblyType = assemblyType;
		this.assemblyNumber = assemblyNumber;
		this.serviceStatus = serviceStatus;
		this.phyStatus = phyStatus;
		this.stationCode = stationCode;
		this.stationName = stationName;
		this.structStatus = structStatus;
		this.servicdeStatus = servicdeStatus;
		this.hostRoomCode = hostRoomCode;
		this.manufacturer = manufacturer;
		this.configurationType = configurationType;
		this.needSnmp = needSnmp;
		this.needTimeSyn = needTimeSyn;
		this.ip = ip;
		this.subnetMask = subnetMask;
		this.gateway = gateway;
		this.temperature = temperature;
		this.longitude = longitude;
		this.targetHost = targetHost;
		this.snmpVersion = snmpVersion;
		this.hostTrapPort = hostTrapPort;
		this.trapEnabled = trapEnabled;
		this.trapHostDomain = trapHostDomain;
		this.capacity = capacity;
		this.insalledCapacity = insalledCapacity;
		this.hight = hight;
		this.isIntergated = isIntergated;
		this.installation = installation;
		this.colsnum = colsnum;
		this.blockEachCol = blockEachCol;
		this.cols = cols;
		this.rows = rows;
		this.dutyPerson = dutyPerson;
		this.oid = oid;
		this.xpositon = xpositon;
		this.ypositon = ypositon;
		this.longtitude = longtitude;
		this.latitude = latitude;
		this.importTag = importTag;
		this.model = model;
		this.type = type;
	}

	public int getIfatId() {
		return this.ifatId;
	}

	public void setIfatId(int ifatId) {
		this.ifatId = ifatId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getAssemblyType() {
		return this.assemblyType;
	}

	public void setAssemblyType(String assemblyType) {
		this.assemblyType = assemblyType;
	}

	public String getAssemblyNumber() {
		return this.assemblyNumber;
	}

	public void setAssemblyNumber(String assemblyNumber) {
		this.assemblyNumber = assemblyNumber;
	}

	public String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public String getPhyStatus() {
		return this.phyStatus;
	}

	public void setPhyStatus(String phyStatus) {
		this.phyStatus = phyStatus;
	}

	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getStructStatus() {
		return this.structStatus;
	}

	public void setStructStatus(String structStatus) {
		this.structStatus = structStatus;
	}

	public String getServicdeStatus() {
		return this.servicdeStatus;
	}

	public void setServicdeStatus(String servicdeStatus) {
		this.servicdeStatus = servicdeStatus;
	}

	public String getHostRoomCode() {
		return this.hostRoomCode;
	}

	public void setHostRoomCode(String hostRoomCode) {
		this.hostRoomCode = hostRoomCode;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getConfigurationType() {
		return this.configurationType;
	}

	public void setConfigurationType(String configurationType) {
		this.configurationType = configurationType;
	}

	public Boolean getNeedSnmp() {
		return this.needSnmp;
	}

	public void setNeedSnmp(Boolean needSnmp) {
		this.needSnmp = needSnmp;
	}

	public Boolean getNeedTimeSyn() {
		return this.needTimeSyn;
	}

	public void setNeedTimeSyn(Boolean needTimeSyn) {
		this.needTimeSyn = needTimeSyn;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getSubnetMask() {
		return this.subnetMask;
	}

	public void setSubnetMask(String subnetMask) {
		this.subnetMask = subnetMask;
	}

	public String getGateway() {
		return this.gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	public Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Integer temperature) {
		this.temperature = temperature;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getTargetHost() {
		return this.targetHost;
	}

	public void setTargetHost(String targetHost) {
		this.targetHost = targetHost;
	}

	public String getSnmpVersion() {
		return this.snmpVersion;
	}

	public void setSnmpVersion(String snmpVersion) {
		this.snmpVersion = snmpVersion;
	}

	public String getHostTrapPort() {
		return this.hostTrapPort;
	}

	public void setHostTrapPort(String hostTrapPort) {
		this.hostTrapPort = hostTrapPort;
	}

	public Boolean getTrapEnabled() {
		return this.trapEnabled;
	}

	public void setTrapEnabled(Boolean trapEnabled) {
		this.trapEnabled = trapEnabled;
	}

	public String getTrapHostDomain() {
		return this.trapHostDomain;
	}

	public void setTrapHostDomain(String trapHostDomain) {
		this.trapHostDomain = trapHostDomain;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getInsalledCapacity() {
		return this.insalledCapacity;
	}

	public void setInsalledCapacity(Integer insalledCapacity) {
		this.insalledCapacity = insalledCapacity;
	}

	public Integer getHight() {
		return this.hight;
	}

	public void setHight(Integer hight) {
		this.hight = hight;
	}

	public Boolean getIsIntergated() {
		return this.isIntergated;
	}

	public void setIsIntergated(Boolean isIntergated) {
		this.isIntergated = isIntergated;
	}

	public String getInstallation() {
		return this.installation;
	}

	public void setInstallation(String installation) {
		this.installation = installation;
	}

	public Integer getColsnum() {
		return this.colsnum;
	}

	public void setColsnum(Integer colsnum) {
		this.colsnum = colsnum;
	}

	public Integer getBlockEachCol() {
		return this.blockEachCol;
	}

	public void setBlockEachCol(Integer blockEachCol) {
		this.blockEachCol = blockEachCol;
	}

	public Integer getCols() {
		return this.cols;
	}

	public void setCols(Integer cols) {
		this.cols = cols;
	}

	public Integer getRows() {
		return this.rows;
	}

	public void setRows(Integer rows) {
		this.rows = rows;
	}

	public String getDutyPerson() {
		return this.dutyPerson;
	}

	public void setDutyPerson(String dutyPerson) {
		this.dutyPerson = dutyPerson;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public Integer getXpositon() {
		return this.xpositon;
	}

	public void setXpositon(Integer xpositon) {
		this.xpositon = xpositon;
	}

	public Integer getYpositon() {
		return this.ypositon;
	}

	public void setYpositon(Integer ypositon) {
		this.ypositon = ypositon;
	}

	public Double getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(Double longtitude) {
		this.longtitude = longtitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
