package com.wanma.domain;

// Generated 2013-12-5 21:53:08 by Hibernate Tools 3.4.0.CR1

/**
 * Obd generated by hbm2java
 */
public class Obd implements java.io.Serializable {

	private int obdId;
	private String name;
	private String code;
	private String parentType;
	private Float splitRatio;
	private String splitLevel;
	private String parentCode;
	private String hostCode;
	private String stationCode;
	private Integer slotNo;
	private String inPortLocation;
	private String stationName;
	private Integer frameNo;
	private Integer obdSeq;
	private String manufacurer;
	private String physicalStatue;
	private String importOs;
	private Integer xpostion;
	private Integer ypostion;
	private Double longitude;
	private Double latitude;
	private Boolean wanmaIodn;
	private String dutyPerson;
	private String oid;
	private String importTag;
	private String type;

	public Obd() {
	}

	public Obd(int obdId, String code) {
		this.obdId = obdId;
		this.code = code;
	}

	public Obd(int obdId, String name, String code, String parentType,
			Float splitRatio, String splitLevel, String parentCode,
			String hostCode, String stationCode, Integer slotNo,
			String inPortLocation, String stationName, Integer frameNo,
			Integer obdSeq, String manufacurer, String physicalStatue,
			String importOs, Integer xpostion, Integer ypostion,
			Double longitude, Double latitude, Boolean wanmaIodn,
			String dutyPerson, String oid, String importTag, String type) {
		this.obdId = obdId;
		this.name = name;
		this.code = code;
		this.parentType = parentType;
		this.splitRatio = splitRatio;
		this.splitLevel = splitLevel;
		this.parentCode = parentCode;
		this.hostCode = hostCode;
		this.stationCode = stationCode;
		this.slotNo = slotNo;
		this.inPortLocation = inPortLocation;
		this.stationName = stationName;
		this.frameNo = frameNo;
		this.obdSeq = obdSeq;
		this.manufacurer = manufacurer;
		this.physicalStatue = physicalStatue;
		this.importOs = importOs;
		this.xpostion = xpostion;
		this.ypostion = ypostion;
		this.longitude = longitude;
		this.latitude = latitude;
		this.wanmaIodn = wanmaIodn;
		this.dutyPerson = dutyPerson;
		this.oid = oid;
		this.importTag = importTag;
		this.type = type;
	}

	public int getObdId() {
		return this.obdId;
	}

	public void setObdId(int obdId) {
		this.obdId = obdId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	public Float getSplitRatio() {
		return this.splitRatio;
	}

	public void setSplitRatio(Float splitRatio) {
		this.splitRatio = splitRatio;
	}

	public String getSplitLevel() {
		return this.splitLevel;
	}

	public void setSplitLevel(String splitLevel) {
		this.splitLevel = splitLevel;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getHostCode() {
		return this.hostCode;
	}

	public void setHostCode(String hostCode) {
		this.hostCode = hostCode;
	}

	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	public Integer getSlotNo() {
		return this.slotNo;
	}

	public void setSlotNo(Integer slotNo) {
		this.slotNo = slotNo;
	}

	public String getInPortLocation() {
		return this.inPortLocation;
	}

	public void setInPortLocation(String inPortLocation) {
		this.inPortLocation = inPortLocation;
	}

	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public Integer getFrameNo() {
		return this.frameNo;
	}

	public void setFrameNo(Integer frameNo) {
		this.frameNo = frameNo;
	}

	public Integer getObdSeq() {
		return this.obdSeq;
	}

	public void setObdSeq(Integer obdSeq) {
		this.obdSeq = obdSeq;
	}

	public String getManufacurer() {
		return this.manufacurer;
	}

	public void setManufacurer(String manufacurer) {
		this.manufacurer = manufacurer;
	}

	public String getPhysicalStatue() {
		return this.physicalStatue;
	}

	public void setPhysicalStatue(String physicalStatue) {
		this.physicalStatue = physicalStatue;
	}

	public String getImportOs() {
		return this.importOs;
	}

	public void setImportOs(String importOs) {
		this.importOs = importOs;
	}

	public Integer getXpostion() {
		return this.xpostion;
	}

	public void setXpostion(Integer xpostion) {
		this.xpostion = xpostion;
	}

	public Integer getYpostion() {
		return this.ypostion;
	}

	public void setYpostion(Integer ypostion) {
		this.ypostion = ypostion;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Boolean getWanmaIodn() {
		return this.wanmaIodn;
	}

	public void setWanmaIodn(Boolean wanmaIodn) {
		this.wanmaIodn = wanmaIodn;
	}

	public String getDutyPerson() {
		return this.dutyPerson;
	}

	public void setDutyPerson(String dutyPerson) {
		this.dutyPerson = dutyPerson;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
