package com.wanma.domain;

// Generated 2013-12-25 15:23:59 by Hibernate Tools 3.4.0.CR1

/**
 * Port generated by hbm2java
 */
public class Port implements java.io.Serializable {

	private int portId;
	private String name;
	private String code;
	private String meType;
	private String meCode;
	private String portType;
	private Integer rowIndex;
	private Integer colIndex;
	private String physicalStatue;
	private String serviceStatue;
	private Integer slotNo;
	private Integer portNo;
	private Integer portSequence;
	private Integer cellNo;
	private String importTag;
	private String parentCode;
	private String preServiceState;

	public Port() {
	}

	public Port(int portId, String code) {
		this.portId = portId;
		this.code = code;
	}

	public Port(int portId, String name, String code, String meType,
			String meCode, String portType, Integer rowIndex, Integer colIndex,
			String physicalStatue, String serviceStatue, Integer slotNo,
			Integer portNo, Integer portSequence, Integer cellNo,
			String importTag, String parentCode, String preServiceState) {
		this.portId = portId;
		this.name = name;
		this.code = code;
		this.meType = meType;
		this.meCode = meCode;
		this.portType = portType;
		this.rowIndex = rowIndex;
		this.colIndex = colIndex;
		this.physicalStatue = physicalStatue;
		this.serviceStatue = serviceStatue;
		this.slotNo = slotNo;
		this.portNo = portNo;
		this.portSequence = portSequence;
		this.cellNo = cellNo;
		this.importTag = importTag;
		this.parentCode = parentCode;
		this.preServiceState = preServiceState;
	}

	public int getPortId() {
		return this.portId;
	}

	public void setPortId(int portId) {
		this.portId = portId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMeType() {
		return this.meType;
	}

	public void setMeType(String meType) {
		this.meType = meType;
	}

	public String getMeCode() {
		return this.meCode;
	}

	public void setMeCode(String meCode) {
		this.meCode = meCode;
	}

	public String getPortType() {
		return this.portType;
	}

	public void setPortType(String portType) {
		this.portType = portType;
	}

	public Integer getRowIndex() {
		return this.rowIndex;
	}

	public void setRowIndex(Integer rowIndex) {
		this.rowIndex = rowIndex;
	}

	public Integer getColIndex() {
		return this.colIndex;
	}

	public void setColIndex(Integer colIndex) {
		this.colIndex = colIndex;
	}

	public String getPhysicalStatue() {
		return this.physicalStatue;
	}

	public void setPhysicalStatue(String physicalStatue) {
		this.physicalStatue = physicalStatue;
	}

	public String getServiceStatue() {
		return this.serviceStatue;
	}

	public void setServiceStatue(String serviceStatue) {
		this.serviceStatue = serviceStatue;
	}

	public Integer getSlotNo() {
		return this.slotNo;
	}

	public void setSlotNo(Integer slotNo) {
		this.slotNo = slotNo;
	}

	public Integer getPortNo() {
		return this.portNo;
	}

	public void setPortNo(Integer portNo) {
		this.portNo = portNo;
	}

	public Integer getPortSequence() {
		return this.portSequence;
	}

	public void setPortSequence(Integer portSequence) {
		this.portSequence = portSequence;
	}

	public Integer getCellNo() {
		return this.cellNo;
	}

	public void setCellNo(Integer cellNo) {
		this.cellNo = cellNo;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getPreServiceState() {
		return this.preServiceState;
	}

	public void setPreServiceState(String preServiceState) {
		this.preServiceState = preServiceState;
	}

}
