package com.wanma.domain;

// Generated 2013-12-18 10:42:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RouteCheckTask generated by hbm2java
 */
public class RouteCheckTask implements java.io.Serializable {

	private String code;
	private String name;
	private String creator;
	private Date createTime;
	private Integer round;
	private Date lastTime;
	private String lastCheckResult;
	private String groupId;
	private String workerId;
	private String deviceCode;
	private String deviceType;
	private String deviceName;
	private Short status;
	private String station;
	private String hostroom;

	public RouteCheckTask() {
	}

	public RouteCheckTask(String code) {
		this.code = code;
	}

	public RouteCheckTask(String code, String name, String creator,
			Date createTime, Integer round, Date lastTime,
			String lastCheckResult, String groupId, String workerId,
			String deviceCode, String deviceType, String deviceName,
			Short status, String station, String hostroom) {
		this.code = code;
		this.name = name;
		this.creator = creator;
		this.createTime = createTime;
		this.round = round;
		this.lastTime = lastTime;
		this.lastCheckResult = lastCheckResult;
		this.groupId = groupId;
		this.workerId = workerId;
		this.deviceCode = deviceCode;
		this.deviceType = deviceType;
		this.deviceName = deviceName;
		this.status = status;
		this.station = station;
		this.hostroom = hostroom;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getRound() {
		return this.round;
	}

	public void setRound(Integer round) {
		this.round = round;
	}

	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	public String getLastCheckResult() {
		return this.lastCheckResult;
	}

	public void setLastCheckResult(String lastCheckResult) {
		this.lastCheckResult = lastCheckResult;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getWorkerId() {
		return this.workerId;
	}

	public void setWorkerId(String workerId) {
		this.workerId = workerId;
	}

	public String getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getHostroom() {
		return this.hostroom;
	}

	public void setHostroom(String hostroom) {
		this.hostroom = hostroom;
	}

}
