package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private String code;
	private String name;
	private String zipCode;
	private String districtName;
	private String briefName;
	private String pinyinName;
	private String address;
	private Double longitude;
	private Double latitude;
	private String notes;
	private String assemblyType;
	private String assemblyNumber;
	private String stationType;
	private String physicalStatue;
	private Integer coverage;
	private Integer floors;
	private Integer structureArea;
	private String assetType;
	private Date createTime;
	private Date reviseTime;
	private String importTag;

	public Station() {
	}

	public Station(String code) {
		this.code = code;
	}

	public Station(String code, String name, String zipCode,
			String districtName, String briefName, String pinyinName,
			String address, Double longitude, Double latitude, String notes,
			String assemblyType, String assemblyNumber, String stationType,
			String physicalStatue, Integer coverage, Integer floors,
			Integer structureArea, String assetType, Date createTime,
			Date reviseTime, String importTag) {
		this.code = code;
		this.name = name;
		this.zipCode = zipCode;
		this.districtName = districtName;
		this.briefName = briefName;
		this.pinyinName = pinyinName;
		this.address = address;
		this.longitude = longitude;
		this.latitude = latitude;
		this.notes = notes;
		this.assemblyType = assemblyType;
		this.assemblyNumber = assemblyNumber;
		this.stationType = stationType;
		this.physicalStatue = physicalStatue;
		this.coverage = coverage;
		this.floors = floors;
		this.structureArea = structureArea;
		this.assetType = assetType;
		this.createTime = createTime;
		this.reviseTime = reviseTime;
		this.importTag = importTag;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public String getBriefName() {
		return this.briefName;
	}

	public void setBriefName(String briefName) {
		this.briefName = briefName;
	}

	public String getPinyinName() {
		return this.pinyinName;
	}

	public void setPinyinName(String pinyinName) {
		this.pinyinName = pinyinName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getAssemblyType() {
		return this.assemblyType;
	}

	public void setAssemblyType(String assemblyType) {
		this.assemblyType = assemblyType;
	}

	public String getAssemblyNumber() {
		return this.assemblyNumber;
	}

	public void setAssemblyNumber(String assemblyNumber) {
		this.assemblyNumber = assemblyNumber;
	}

	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	public String getPhysicalStatue() {
		return this.physicalStatue;
	}

	public void setPhysicalStatue(String physicalStatue) {
		this.physicalStatue = physicalStatue;
	}

	public Integer getCoverage() {
		return this.coverage;
	}

	public void setCoverage(Integer coverage) {
		this.coverage = coverage;
	}

	public Integer getFloors() {
		return this.floors;
	}

	public void setFloors(Integer floors) {
		this.floors = floors;
	}

	public Integer getStructureArea() {
		return this.structureArea;
	}

	public void setStructureArea(Integer structureArea) {
		this.structureArea = structureArea;
	}

	public String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getReviseTime() {
		return this.reviseTime;
	}

	public void setReviseTime(Date reviseTime) {
		this.reviseTime = reviseTime;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
