package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * StationFiberLink generated by hbm2java
 */
public class StationFiberLink implements java.io.Serializable {

	private int stationFiberLinkId;
	private String parentCode;
	private String cableSet;
	private Integer logicNo;
	private Integer fiberSque;
	private String importTag;

	public StationFiberLink() {
	}

	public StationFiberLink(int stationFiberLinkId) {
		this.stationFiberLinkId = stationFiberLinkId;
	}

	public StationFiberLink(int stationFiberLinkId, String parentCode,
			String cableSet, Integer logicNo, Integer fiberSque,
			String importTag) {
		this.stationFiberLinkId = stationFiberLinkId;
		this.parentCode = parentCode;
		this.cableSet = cableSet;
		this.logicNo = logicNo;
		this.fiberSque = fiberSque;
		this.importTag = importTag;
	}

	public int getStationFiberLinkId() {
		return this.stationFiberLinkId;
	}

	public void setStationFiberLinkId(int stationFiberLinkId) {
		this.stationFiberLinkId = stationFiberLinkId;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getCableSet() {
		return this.cableSet;
	}

	public void setCableSet(String cableSet) {
		this.cableSet = cableSet;
	}

	public Integer getLogicNo() {
		return this.logicNo;
	}

	public void setLogicNo(Integer logicNo) {
		this.logicNo = logicNo;
	}

	public Integer getFiberSque() {
		return this.fiberSque;
	}

	public void setFiberSque(Integer fiberSque) {
		this.fiberSque = fiberSque;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
