package com.wanma.domain;

// Generated 2013-12-16 9:35:27 by Hibernate Tools 3.4.0.CR1

/**
 * TerminalUnit generated by hbm2java
 */
public class TerminalUnit implements java.io.Serializable {

	private int terminalUnitId;
	private String terminalUnitName;
	private String terminalUnitCode;
	private String hostDeviceId;
	private Integer terminalNum;
	private Integer occupiedNum;
	private Integer damagedNum;
	private Integer columnNumber;
	private Integer rowNumber;
	private Integer originalFrame;
	private Integer frameNum;
	private String status;
	private String type;
	private String terminalUnitSeq;

	public TerminalUnit() {
	}

	public TerminalUnit(int terminalUnitId, String terminalUnitName) {
		this.terminalUnitId = terminalUnitId;
		this.terminalUnitName = terminalUnitName;
	}

	public TerminalUnit(int terminalUnitId, String terminalUnitName,
			String terminalUnitCode, String hostDeviceId, Integer terminalNum,
			Integer occupiedNum, Integer damagedNum, Integer columnNumber,
			Integer rowNumber, Integer originalFrame, Integer frameNum,
			String status, String type, String terminalUnitSeq) {
		this.terminalUnitId = terminalUnitId;
		this.terminalUnitName = terminalUnitName;
		this.terminalUnitCode = terminalUnitCode;
		this.hostDeviceId = hostDeviceId;
		this.terminalNum = terminalNum;
		this.occupiedNum = occupiedNum;
		this.damagedNum = damagedNum;
		this.columnNumber = columnNumber;
		this.rowNumber = rowNumber;
		this.originalFrame = originalFrame;
		this.frameNum = frameNum;
		this.status = status;
		this.type = type;
		this.terminalUnitSeq = terminalUnitSeq;
	}

	public int getTerminalUnitId() {
		return this.terminalUnitId;
	}

	public void setTerminalUnitId(int terminalUnitId) {
		this.terminalUnitId = terminalUnitId;
	}

	public String getTerminalUnitName() {
		return this.terminalUnitName;
	}

	public void setTerminalUnitName(String terminalUnitName) {
		this.terminalUnitName = terminalUnitName;
	}

	public String getTerminalUnitCode() {
		return this.terminalUnitCode;
	}

	public void setTerminalUnitCode(String terminalUnitCode) {
		this.terminalUnitCode = terminalUnitCode;
	}

	public String getHostDeviceId() {
		return this.hostDeviceId;
	}

	public void setHostDeviceId(String hostDeviceId) {
		this.hostDeviceId = hostDeviceId;
	}

	public Integer getTerminalNum() {
		return this.terminalNum;
	}

	public void setTerminalNum(Integer terminalNum) {
		this.terminalNum = terminalNum;
	}

	public Integer getOccupiedNum() {
		return this.occupiedNum;
	}

	public void setOccupiedNum(Integer occupiedNum) {
		this.occupiedNum = occupiedNum;
	}

	public Integer getDamagedNum() {
		return this.damagedNum;
	}

	public void setDamagedNum(Integer damagedNum) {
		this.damagedNum = damagedNum;
	}

	public Integer getColumnNumber() {
		return this.columnNumber;
	}

	public void setColumnNumber(Integer columnNumber) {
		this.columnNumber = columnNumber;
	}

	public Integer getRowNumber() {
		return this.rowNumber;
	}

	public void setRowNumber(Integer rowNumber) {
		this.rowNumber = rowNumber;
	}

	public Integer getOriginalFrame() {
		return this.originalFrame;
	}

	public void setOriginalFrame(Integer originalFrame) {
		this.originalFrame = originalFrame;
	}

	public Integer getFrameNum() {
		return this.frameNum;
	}

	public void setFrameNum(Integer frameNum) {
		this.frameNum = frameNum;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTerminalUnitSeq() {
		return this.terminalUnitSeq;
	}

	public void setTerminalUnitSeq(String terminalUnitSeq) {
		this.terminalUnitSeq = terminalUnitSeq;
	}

}
