package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * ToStationFiber generated by hbm2java
 */
public class ToStationFiber implements java.io.Serializable {

	private String code;
	private String name;
	private String ameCode;
	private String aportCode;
	private String zmeCode;
	private String zportCode;
	private String serviceStatue;
	private Integer length;
	private int toStationFiberId;
	private String importTag;

	public ToStationFiber() {
	}

	public ToStationFiber(String code, String name, int toStationFiberId) {
		this.code = code;
		this.name = name;
		this.toStationFiberId = toStationFiberId;
	}

	public ToStationFiber(String code, String name, String ameCode,
			String aportCode, String zmeCode, String zportCode,
			String serviceStatue, Integer length, int toStationFiberId,
			String importTag) {
		this.code = code;
		this.name = name;
		this.ameCode = ameCode;
		this.aportCode = aportCode;
		this.zmeCode = zmeCode;
		this.zportCode = zportCode;
		this.serviceStatue = serviceStatue;
		this.length = length;
		this.toStationFiberId = toStationFiberId;
		this.importTag = importTag;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAmeCode() {
		return this.ameCode;
	}

	public void setAmeCode(String ameCode) {
		this.ameCode = ameCode;
	}

	public String getAportCode() {
		return this.aportCode;
	}

	public void setAportCode(String aportCode) {
		this.aportCode = aportCode;
	}

	public String getZmeCode() {
		return this.zmeCode;
	}

	public void setZmeCode(String zmeCode) {
		this.zmeCode = zmeCode;
	}

	public String getZportCode() {
		return this.zportCode;
	}

	public void setZportCode(String zportCode) {
		this.zportCode = zportCode;
	}

	public String getServiceStatue() {
		return this.serviceStatue;
	}

	public void setServiceStatue(String serviceStatue) {
		this.serviceStatue = serviceStatue;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public int getToStationFiberId() {
		return this.toStationFiberId;
	}

	public void setToStationFiberId(int toStationFiberId) {
		this.toStationFiberId = toStationFiberId;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
