package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * UserOdn generated by hbm2java
 */
public class UserOdn implements java.io.Serializable {

	private String userName;
	private String phoneNum;
	private String realName;
	private String groupName;
	private String password;
	private String userType;
	private String email;
	private String gengHao;

	public UserOdn() {
	}

	public UserOdn(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public UserOdn(String userName, String phoneNum, String realName,
			String groupName, String password, String userType, String email,
			String gengHao) {
		this.userName = userName;
		this.phoneNum = phoneNum;
		this.realName = realName;
		this.groupName = groupName;
		this.password = password;
		this.userType = userType;
		this.email = email;
		this.gengHao = gengHao;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGengHao() {
		return this.gengHao;
	}

	public void setGengHao(String gengHao) {
		this.gengHao = gengHao;
	}

}
