package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * WeldConnector generated by hbm2java
 */
public class WeldConnector implements java.io.Serializable {

	private int weldConnectorId;
	private String meType;
	private String meCode;
	private String acableSectionCode;
	private Integer afiberNo;
	private String zcableSectionCode;
	private Integer zfiberNo;
	private String importTag;

	public WeldConnector() {
	}

	public WeldConnector(int weldConnectorId, String meCode) {
		this.weldConnectorId = weldConnectorId;
		this.meCode = meCode;
	}

	public WeldConnector(int weldConnectorId, String meType, String meCode,
			String acableSectionCode, Integer afiberNo,
			String zcableSectionCode, Integer zfiberNo, String importTag) {
		this.weldConnectorId = weldConnectorId;
		this.meType = meType;
		this.meCode = meCode;
		this.acableSectionCode = acableSectionCode;
		this.afiberNo = afiberNo;
		this.zcableSectionCode = zcableSectionCode;
		this.zfiberNo = zfiberNo;
		this.importTag = importTag;
	}

	public int getWeldConnectorId() {
		return this.weldConnectorId;
	}

	public void setWeldConnectorId(int weldConnectorId) {
		this.weldConnectorId = weldConnectorId;
	}

	public String getMeType() {
		return this.meType;
	}

	public void setMeType(String meType) {
		this.meType = meType;
	}

	public String getMeCode() {
		return this.meCode;
	}

	public void setMeCode(String meCode) {
		this.meCode = meCode;
	}

	public String getAcableSectionCode() {
		return this.acableSectionCode;
	}

	public void setAcableSectionCode(String acableSectionCode) {
		this.acableSectionCode = acableSectionCode;
	}

	public Integer getAfiberNo() {
		return this.afiberNo;
	}

	public void setAfiberNo(Integer afiberNo) {
		this.afiberNo = afiberNo;
	}

	public String getZcableSectionCode() {
		return this.zcableSectionCode;
	}

	public void setZcableSectionCode(String zcableSectionCode) {
		this.zcableSectionCode = zcableSectionCode;
	}

	public Integer getZfiberNo() {
		return this.zfiberNo;
	}

	public void setZfiberNo(Integer zfiberNo) {
		this.zfiberNo = zfiberNo;
	}

	public String getImportTag() {
		return this.importTag;
	}

	public void setImportTag(String importTag) {
		this.importTag = importTag;
	}

}
