package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * WorkGroupId generated by hbm2java
 */
public class WorkGroupId implements java.io.Serializable {

	private String groupName;
	private String ownerName;

	public WorkGroupId() {
	}

	public WorkGroupId(String groupName, String ownerName) {
		this.groupName = groupName;
		this.ownerName = ownerName;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkGroupId))
			return false;
		WorkGroupId castOther = (WorkGroupId) other;

		return ((this.getGroupName() == castOther.getGroupName()) || (this
				.getGroupName() != null && castOther.getGroupName() != null && this
				.getGroupName().equals(castOther.getGroupName())))
				&& ((this.getOwnerName() == castOther.getOwnerName()) || (this
						.getOwnerName() != null
						&& castOther.getOwnerName() != null && this
						.getOwnerName().equals(castOther.getOwnerName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGroupName() == null ? 0 : this.getGroupName().hashCode());
		result = 37 * result
				+ (getOwnerName() == null ? 0 : this.getOwnerName().hashCode());
		return result;
	}

}
