package com.wanma.domain;

// Generated 2013-10-30 7:44:51 by Hibernate Tools 3.4.0.CR1

/**
 * WorkGroup generated by hbm2java
 */
public class WorkGroup implements java.io.Serializable {

	private WorkGroupId id;
	private String groupLeader;

	public WorkGroup() {
	}

	public WorkGroup(WorkGroupId id) {
		this.id = id;
	}

	public WorkGroup(WorkGroupId id, String groupLeader) {
		this.id = id;
		this.groupLeader = groupLeader;
	}

	public WorkGroupId getId() {
		return this.id;
	}

	public void setId(WorkGroupId id) {
		this.id = id;
	}

	public String getGroupLeader() {
		return this.groupLeader;
	}

	public void setGroupLeader(String groupLeader) {
		this.groupLeader = groupLeader;
	}

}
